#pragma once

#define RISCV_SIM_CMD_OPCODE 0b1101011
#define RISCV_SIM_SHOW_REGISTERS_FUNCT  0
#define RISCV_SIM_SHOW_VREGISTERS_FUNCT 1
#define RISCV_SIM_SHOW_CYCLES_FUNCT     2
#define RISCV_SIM_RESET_HPC_FUNCT       3
#define RISCV_SIM_SHOW_HPC_FUNCT        4
#define RISCV_SIM_PRINT_INT_FUNCT       5
#define RISCV_SIM_PRINT_STR_FUNCT       6
#define RISCV_TRACING_TRIGGER_TOGGLE    7
